### ISSUE TITLE
After the supervisor runs horizon for a period of time, redis reports an error: read error on connection

### ISSUE THREAD

**Issue by srako** [laravel/horizon#1041]
- Horizon Version: 3.7.2
- Laravel Version: 6.20.30
- PHP Version: 7.2.34
- Redis Driver & Version: phpredis
- Database Driver & Version:10.0.27-MariaDB

### Description:
``` php
message: read error on connection
RedisException: read error on connection in /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116 Stack trace: #0 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Redis->hMset('463', Array) #1 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(513): Illuminate\Redis\Connections\Connection->command('hmset', Array) #2 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(136): Illuminate\Redis\Connections\PhpRedisConnection->command('hmset', Array) #3 /data/www/one/vendor/laravel/horizon/src/Repositories/RedisJobRepository.php(304): Illuminate\Redis\Connections\PhpRedisConnection->hmset('463', Array) #4 /data/www/one/vendor/laravel/horizon/src/Listeners/MarkJobAsReserved.php(36): Laravel\Horizon\Repositories\RedisJobRepository->reserved('rabbitmq', 'one', Object(Laravel\Horizon\JobPayload)) #5 /data/www/one/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(389): Laravel\Horizon\Listeners\MarkJobAsReserved->handle(Object(Laravel\Horizon\Events\JobReserved)) #6 /data/www/one/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events{closure}('Laravel\Horizon...', Array) #7 /data/www/one/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(118): Illuminate\Events\Dispatcher->dispatch('Laravel\Horizon...') #8 /data/www/one/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(78): VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue->event('one', Object(Laravel\Horizon\Events\JobReserved)) #9 /data/www/one/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue->VladimirYuldashev\LaravelQueueRabbitMQ\Horizon{closure}(Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob)) #10 /data/www/one/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(80): tap(Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), Object(Closure)) #11 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(284): VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue->pop('one') #12 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(123): Illuminate\Queue\Worker->getNextJob(Object(VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue), 'one') #13 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('rabbitmq', 'one', Object(Illuminate\Queue\WorkerOptions)) #14 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('rabbitmq', 'one') #15 /data/www/one/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle() #16 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle() #17 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #18 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure)) #19 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #20 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #21 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array) #22 /data/www/one/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #23 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #24 /data/www/one/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #25 /data/www/one/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #26 /data/www/one/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #27 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #28 /data/www/one/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #29 /data/www/one/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #30 {main}
```

### Steps To Reproduce:

* Redis configuration
```php
// config/database.php
'redis' => [
        'client' => env('REDIS_CLIENT', 'phpredis'),

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],

        'queue' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_QUEUE_DB', 1),
            'retry_interval' => 200,
        ],
    ],

```

* Horizon configuration
```php
 //  config/horizon.php 
[
   'domain' => null,
    'path' => 'horizon',
    'use' => 'queue',
    'prefix' => env('HORIZON_PREFIX', 'horizon:'),
    'middleware' => ['web'],
    'waits' => [
        'redis:one' => 60,
        'rabbitmq:one' => 120,
    ],
    'trim' => [
        'recent' => 60,
        'completed' => 60,
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
    ],
    'fast_termination' => false,

    'memory_limit' => 128,
    'environments' => [
        'production' => [
            'supervisor-1' => [
                'connection' => 'rabbitmq',
                'queue' => [env('RABBITMQ_QUEUE', 'one')],
                'balance' => 'auto',
                'processes' => 10,
                'tries' => 3,
                'timeout'=>120
            ],
        ],

        'preview' => [
            'supervisor-1' => [
                'connection' => 'rabbitmq',
                'queue' => [env('RABBITMQ_QUEUE', 'one')],
                'balance' => 'auto',
                'processes' => 10,
                'tries' => 3,
                'timeout'=>120,
            ],
        ],

        'test' => [
            'supervisor-1' => [
                'connection' => 'rabbitmq',
                'queue' => [env('RABBITMQ_QUEUE', 'one')],
                'balance' => 'auto',
                'processes' => 5,
                'tries' => 1,
                'timeout'=>120,
            ],
        ]
    ],
]
```

* Supervisor configuration
``` ini
# horizon.ini
[program:horizon]
process_name=%(program_name)s
command=/usr/local/php/bin/php /data/www/one/artisan horizon
autostart=true
autorestart=true
user=deploy
redirect_stderr=true
stdout_logfile=/data/logs/www/one.shhzcj.com/horizon.log
```

**Comment by halaei** [comment]
The stack you send belongs to a different project https://github.com/vyuldashev/laravel-queue-rabbitmq

> #7 /data/www/one/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(118): Illuminate\Events\Dispatcher->dispatch('Laravel\Horizon...')

So it is not a laravel/horizon issue I guess.

**Comment by srako** [comment]
> The stack you send belongs to a different project https://github.com/vyuldashev/laravel-queue-rabbitmq
> 
> > 
> 
> ```
> #7 /data/www/one/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(118): Illuminate\Events\Dispatcher->dispatch('Laravel\Horizon...')
> ```
> 
> So it is not a laravel/horizon issue I guess.

* 1、 When I use predis as the driver
```php
message: Error while reading line from the server. [tcp://192.168.158.50:6379]
Predis\Connection\ConnectionException: Error while reading line from the server. [tcp://192.168.158.50:6379] in /data/www/one/vendor/predis/predis/src/Connection/AbstractConnection.php:155 Stack trace: #0 /data/www/one/vendor/predis/predis/src/Connection/StreamConnection.php(314): Predis\Connection\AbstractConnection->onConnectionError('Error while rea...') #1 /data/www/one/vendor/predis/predis/src/Connection/AbstractConnection.php(120): Predis\Connection\StreamConnection->read() #2 /data/www/one/vendor/predis/predis/src/Connection/AbstractConnection.php(112): Predis\Connection\AbstractConnection->readResponse(Object(Predis\Command\HashSetMultiple)) #3 /data/www/one/vendor/predis/predis/src/Client.php(331): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\HashSetMultiple)) #4 /data/www/one/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\HashSetMultiple)) #5 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\Client->call('hmset', Array) #6 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\Redis\Connections\Connection->command('hmset', Array) #7 /data/www/one/vendor/laravel/horizon/src/Repositories/RedisJobRepository.php(304): Illuminate\Redis\Connections\Connection->call('hmset', Array) #8 /data/www/one/vendor/laravel/horizon/src/Listeners/MarkJobAsReserved.php(36): Laravel\Horizon\Repositories\RedisJobRepository->reserved('redis', 'one', Object(Laravel\Horizon\JobPayload)) #9 /data/www/one/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(389): Laravel\Horizon\Listeners\MarkJobAsReserved->handle(Object(Laravel\Horizon\Events\JobReserved)) #10 /data/www/one/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events{closure}('Laravel\Horizon...', Array) #11 /data/www/one/vendor/laravel/horizon/src/RedisQueue.php(155): Illuminate\Events\Dispatcher->dispatch('Laravel\Horizon...') #12 /data/www/one/vendor/laravel/horizon/src/RedisQueue.php(94): Laravel\Horizon\RedisQueue->event('one', Object(Laravel\Horizon\Events\JobReserved)) #13 /data/www/one/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Laravel\Horizon\RedisQueue->Laravel\Horizon{closure}(Object(Illuminate\Queue\Jobs\RedisJob)) #14 /data/www/one/vendor/laravel/horizon/src/RedisQueue.php(96): tap(Object(Illuminate\Queue\Jobs\RedisJob), Object(Closure)) #15 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(284): Laravel\Horizon\RedisQueue->pop('one') #16 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(123): Illuminate\Queue\Worker->getNextJob(Object(Laravel\Horizon\RedisQueue), 'one') #17 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'one', Object(Illuminate\Queue\WorkerOptions)) #18 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'one') #19 /data/www/one/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle() #20 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle() #21 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #22 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure)) #23 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #24 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #25 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array) #26 /data/www/one/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #27 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #28 /data/www/one/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #29 /data/www/one/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #30 /data/www/one/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #31 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #32 /data/www/one/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #33 /data/www/one/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #34 {main}
```

* 2、When I use phpredis as the driver

```php 
message: read error on connection
RedisException: read error on connection in /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116 Stack trace: #0 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Redis->hMset('62', Array) #1 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(513): Illuminate\Redis\Connections\Connection->command('hmset', Array) #2 /data/www/one/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(136): Illuminate\Redis\Connections\PhpRedisConnection->command('hmset', Array) #3 /data/www/one/vendor/laravel/horizon/src/Repositories/RedisJobRepository.php(304): Illuminate\Redis\Connections\PhpRedisConnection->hmset('62', Array) #4 /data/www/one/vendor/laravel/horizon/src/Listeners/MarkJobAsReserved.php(36): Laravel\Horizon\Repositories\RedisJobRepository->reserved('redis', 'one', Object(Laravel\Horizon\JobPayload)) #5 /data/www/one/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(389): Laravel\Horizon\Listeners\MarkJobAsReserved->handle(Object(Laravel\Horizon\Events\JobReserved)) #6 /data/www/one/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events{closure}('Laravel\Horizon...', Array) #7 /data/www/one/vendor/laravel/horizon/src/RedisQueue.php(155): Illuminate\Events\Dispatcher->dispatch('Laravel\Horizon...') #8 /data/www/one/vendor/laravel/horizon/src/RedisQueue.php(94): Laravel\Horizon\RedisQueue->event('one', Object(Laravel\Horizon\Events\JobReserved)) #9 /data/www/one/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Laravel\Horizon\RedisQueue->Laravel\Horizon{closure}(Object(Illuminate\Queue\Jobs\RedisJob)) #10 /data/www/one/vendor/laravel/horizon/src/RedisQueue.php(96): tap(Object(Illuminate\Queue\Jobs\RedisJob), Object(Closure)) #11 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(284): Laravel\Horizon\RedisQueue->pop('one') #12 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(123): Illuminate\Queue\Worker->getNextJob(Object(Laravel\Horizon\RedisQueue), 'one') #13 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('redis', 'one', Object(Illuminate\Queue\WorkerOptions)) #14 /data/www/one/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'one') #15 /data/www/one/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle() #16 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle() #17 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #18 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure)) #19 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #20 /data/www/one/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #21 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array) #22 /data/www/one/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #23 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #24 /data/www/one/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #25 /data/www/one/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #26 /data/www/one/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #27 /data/www/one/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #28 /data/www/one/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #29 /data/www/one/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #30 {main}
```

**Comment by halaei** [comment]
Based on you horizon config ('use' => 'queue'), you may have issue connecting to 'queue' redis connection defined in database.php.
Check the output of this:

    dd(\Illuminate\Support\Facades\Redis::connection('queue')->ping());

**Comment by srako** [comment]
When the service first started running, everything was normal. After waiting for an hour, this error will appear. Explain that it should not be a configuration problem of redis

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by EdgarSedov** [comment]
try to set block_for with non-zero integer value for worker
