### ISSUE TITLE
production.ERROR: Command 'SHOULDREPORT' is not a registered Redis command. {"exception":"[object] (Predis\\ClientException(code: 0): Command 'SHOULDREPORT' is not a registered Redis command. at RedisProfile.php:88)

### ISSUE THREAD

**Issue by spidgorny** [laravel/horizon#1056]
- Horizon Version: 4.3.5
- Laravel Version: 7.30.4
- PHP Version: 7.3
- Redis Driver & Version: predis/phpredis 1.1.6
- Database Driver & Version: mysql

### Description:

I see the following in my error log from time to time. I could not find the string 'SHOULDREPORT' anywhere in the source code, but somehow it's still appears in the error log regularly. Any ideas where it may come from?

```
Aug 18 14:45:36 CoreLinuxServer php [2021-08-18 08:45:36] production.ERROR: Command 'SHOULDREPORT' is not a registered Redis command. {"exception":"[object] (Predis\\ClientException(code: 0): Command 'SHOULDREPORT' is not a registered Redis command. at /var/www/production/html/vendor/predis/predis/src/Profile/RedisProfile.php:88)
Aug 18 14:45:36 CoreLinuxServer php [stacktrace]
Aug 18 14:45:36 CoreLinuxServer php #0 /var/www/production/html/vendor/predis/predis/src/Client.php(323): Predis\\Profile\\RedisProfile->createCommand()
Aug 18 14:45:36 CoreLinuxServer php #1 /var/www/production/html/vendor/predis/predis/src/Pipeline/Pipeline.php(59): Predis\\Client->createCommand()
Aug 18 14:45:36 CoreLinuxServer php #2 /var/www/production/html/vendor/predis/predis/src/Pipeline/Pipeline.php(130): Predis\\Pipeline\\Pipeline->__call()
Aug 18 14:45:36 CoreLinuxServer php #3 /var/www/production/html/vendor/predis/predis/src/Pipeline/Pipeline.php(165): Predis\\Pipeline\\Pipeline->executePipeline()
Aug 18 14:45:36 CoreLinuxServer php #4 /var/www/production/html/vendor/predis/predis/src/Pipeline/Pipeline.php(214): Predis\\Pipeline\\Pipeline->flushPipeline()
Aug 18 14:45:36 CoreLinuxServer php #5 /var/www/production/html/vendor/predis/predis/src/Client.php(445): Predis\\Pipeline\\Pipeline->execute()
Aug 18 14:45:36 CoreLinuxServer php #6 /var/www/production/html/vendor/predis/predis/src/Client.php(396): Predis\\Client->createPipeline()
Aug 18 14:45:36 CoreLinuxServer php #7 /var/www/production/html/vendor/predis/predis/src/Client.php(418): Predis\\Client->sharedContextFactory()
Aug 18 14:45:36 CoreLinuxServer php #8 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->pipeline()
Aug 18 14:45:36 CoreLinuxServer php #9 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\Connection->command()
Aug 18 14:45:36 CoreLinuxServer php #10 /var/www/production/html/vendor/laravel/horizon/src/Repositories/RedisJobRepository.php(462): Illuminate\\Redis\\Connections\\Connection->__call()
Aug 18 14:45:36 CoreLinuxServer php #11 /var/www/production/html/vendor/laravel/horizon/src/Listeners/MarkJobAsComplete.php(46): Laravel\\Horizon\\Repositories\\RedisJobRepository->completed()
Aug 18 14:45:36 CoreLinuxServer php #12 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(401): Laravel\\Horizon\\Listeners\\MarkJobAsComplete->handle()
Aug 18 14:45:36 CoreLinuxServer php #13 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
Aug 18 14:45:36 CoreLinuxServer php #14 /var/www/production/html/vendor/laravel/horizon/src/RedisQueue.php(155): Illuminate\\Events\\Dispatcher->dispatch()
Aug 18 14:45:36 CoreLinuxServer php #15 /var/www/production/html/vendor/laravel/horizon/src/RedisQueue.php(124): Laravel\\Horizon\\RedisQueue->event()
Aug 18 14:45:36 CoreLinuxServer php #16 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(84): Laravel\\Horizon\\RedisQueue->deleteReserved()
Aug 18 14:45:36 CoreLinuxServer php #17 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(66): Illuminate\\Queue\\Jobs\\RedisJob->delete()
Aug 18 14:45:36 CoreLinuxServer php #18 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
Aug 18 14:45:36 CoreLinuxServer php #19 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
Aug 18 14:45:36 CoreLinuxServer php #20 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process()
Aug 18 14:45:36 CoreLinuxServer php #21 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob()
Aug 18 14:45:36 CoreLinuxServer php #22 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
Aug 18 14:45:36 CoreLinuxServer php #23 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
Aug 18 14:45:36 CoreLinuxServer php #24 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
Aug 18 14:45:36 CoreLinuxServer php #25 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
Aug 18 14:45:36 CoreLinuxServer php #26 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
Aug 18 14:45:36 CoreLinuxServer php #27 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
Aug 18 14:45:36 CoreLinuxServer php #28 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
Aug 18 14:45:36 CoreLinuxServer php #29 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
Aug 18 14:45:36 CoreLinuxServer php #30 /var/www/production/html/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
Aug 18 14:45:36 CoreLinuxServer php #31 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
Aug 18 14:45:36 CoreLinuxServer php #32 /var/www/production/html/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
Aug 18 14:45:36 CoreLinuxServer php #33 /var/www/production/html/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
Aug 18 14:45:36 CoreLinuxServer php #34 /var/www/production/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
Aug 18 14:45:36 CoreLinuxServer php #35 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
Aug 18 14:45:36 CoreLinuxServer php #36 /var/www/production/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
Aug 18 14:45:36 CoreLinuxServer php #37 /var/www/production/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
Aug 18 14:45:36 CoreLinuxServer php #38 {main}
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
