### ISSUE TITLE
ZSetReverseRangeByScore error

### ISSUE THREAD

**Issue by psjavi** [laravel/horizon#1147]
- Horizon Version: 5.9.6
- Laravel Version: 9.4.0
- PHP Version: 8.1.5
- Redis Driver & Version: phpredis
- Database Driver & Version: Mysql

### Description:
Hi, I'm having a lot of errors every second and I don't know how to solve it.

I've supervisor installed in order to execute the daemon automatically.

How can I solve this issue?

```2022-04-19 10:53:29	include(/var/www/vhosts/myApp/vendor/composer/../predis/predis/src/Command/ZSetReverseRangeByScore.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/var/www/vhosts/myApp/vendor/composer/../predis/predis/src/Command/ZSetReverseRangeByScore.php): Failed to open stream: No such file or directory at /var/www/vhosts/myApp/vendor/composer/ClassLoader.php:571)
[stacktrace]
#0 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/vhosts/myApp/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/vhosts/myApp/vendor/composer/ClassLoader.php(571): include('...')
#3 /var/www/vhosts/myApp/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile()
#4 /var/www/vhosts/myApp/vendor/predis/predis/src/Profile/RedisProfile.php(92): Composer\\Autoload\\ClassLoader->loadClass()
#5 /var/www/vhosts/myApp/vendor/predis/predis/src/Client.php(323): Predis\\Profile\\RedisProfile->createCommand()
#6 /var/www/vhosts/myApp/vendor/predis/predis/src/Client.php(314): Predis\\Client->createCommand()
#7 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call()
#8 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\Connection->command()
#9 /var/www/vhosts/myApp/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(39): Illuminate\\Redis\\Connections\\Connection->__call()
#10 /var/www/vhosts/myApp/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(50): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->names()
#11 /var/www/vhosts/myApp/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(99): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->all()
#12 /var/www/vhosts/myApp/vendor/laravel/horizon/src/MasterSupervisor.php(165): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->longestActiveTimeout()
#13 /var/www/vhosts/myApp/vendor/laravel/horizon/src/ListensForSignals.php(52): Laravel\\Horizon\\MasterSupervisor->terminate()
#14 /var/www/vhosts/myApp/vendor/laravel/horizon/src/MasterSupervisor.php(238): Laravel\\Horizon\\MasterSupervisor->processPendingSignals()
#15 /var/www/vhosts/myApp/vendor/laravel/horizon/src/MasterSupervisor.php(212): Laravel\\Horizon\\MasterSupervisor->loop()
#16 /var/www/vhosts/myApp/vendor/laravel/horizon/src/Console/HorizonCommand.php(56): Laravel\\Horizon\\MasterSupervisor->monitor()
#17 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\HorizonCommand->handle()
#18 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#20 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#22 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#23 /var/www/vhosts/myApp/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#24 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#25 /var/www/vhosts/myApp/vendor/symfony/console/Application.php(989): Illuminate\\Console\\Command->run()
#26 /var/www/vhosts/myApp/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#27 /var/www/vhosts/myApp/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#28 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#29 /var/www/vhosts/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#30 /var/www/vhosts/myApp/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#31 {main}
"}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
