### ISSUE TITLE
Laravel\Horizon\Repositories\RedisMasterSupervisorRepository::__construct(): Argument #1 ($redis) must be of type Illuminate\Contracts\Redis\Factory, Illuminate\Redis\RedisManager given

### ISSUE THREAD

**Issue by Noogic** [laravel/horizon#1243]
- Horizon Version: 5.14.0
- Laravel Version: 9.50.2
- PHP Version: 8.2.1
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:
I just found the error on Sentry after updating the horizon package

```
TypeError: Laravel\Horizon\Repositories\RedisMasterSupervisorRepository::__construct(): Argument #1 ($redis) must be of type Illuminate\Contracts\Redis\Factory, Illuminate\Redis\RedisManager given
#72 /vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(27): Laravel\Horizon\Repositories\RedisMasterSupervisorRepository::__construct
#71 [internal](0): ReflectionClass::newInstanceArgs
#70 /vendor/laravel/framework/src/Illuminate/Container/Container.php(929): Illuminate\Container\Container::build
#69 /vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container::resolve
#68 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Foundation\Application::resolve
#67 /vendor/laravel/framework/src/Illuminate/Container/Container.php(295): Illuminate\Container\Container::Illuminate\Container\{closure}
#66 /vendor/laravel/framework/src/Illuminate/Container/Container.php(885): Illuminate\Container\Container::build
#65 /vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container::resolve
#64 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Foundation\Application::resolve
#63 /vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\Container\Container::make
#62 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Foundation\Application::make
#61 /vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(85): Illuminate\Routing\ControllerDispatcher::transformDependency
#60 /vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(50): Illuminate\Routing\ControllerDispatcher::resolveMethodDependencies
#59 /vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(29): Illuminate\Routing\ControllerDispatcher::resolveClassMethodDependencies
#58 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(59): Illuminate\Routing\ControllerDispatcher::resolveParameters
#57 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(40): Illuminate\Routing\ControllerDispatcher::dispatch
#56 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(21): Sentry\Laravel\Tracing\Routing\TracingControllerDispatcherTracing::Sentry\Laravel\Tracing\Routing\{closure}
#55 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php(31): Sentry\Laravel\Tracing\Routing\TracingRoutingDispatcher::wrapRouteDispatch
#54 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(20): Sentry\Laravel\Tracing\Routing\TracingControllerDispatcherTracing::dispatch
#53 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\Route::runController
#52 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route::run
#51 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#50 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#49 /vendor/laravel/horizon/src/Http/Middleware/Authenticate.php(18): Laravel\Horizon\Http\Middleware\Authenticate::handle
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#47 /vendor/laravel/framework/src/Illuminate/Http/Middleware/AddLinkHeadersForPreloadedAssets.php(19): Illuminate\Http\Middleware\AddLinkHeadersForPreloadedAssets::handle
#46 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#45 /vendor/inertiajs/inertia-laravel/src/Middleware.php(87): Inertia\Middleware::handle
#44 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#43 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Routing\Middleware\SubstituteBindings::handle
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#41 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
#40 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#39 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\View\Middleware\ShareErrorsFromSession::handle
#38 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#37 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Session\Middleware\StartSession::handleStatefulRequest
#36 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession::handle
#35 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#34 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
#33 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#32 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Cookie\Middleware\EncryptCookies::handle
#31 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#30 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline::then
#29 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\Routing\Router::runRouteWithinStack
#28 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router::runRoute
#27 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router::dispatchToRoute
#26 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\Routing\Router::dispatch
#25 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php(45): Sentry\Laravel\Http\SetRequestIpMiddleware::handle
#22 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#21 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(30): Sentry\Laravel\Http\SetRequestMiddleware::handle
#20 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#19 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#18 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::handle
#17 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#16 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#15 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TrimStrings::handle
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#13 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Foundation\Http\Middleware\ValidatePostSize::handle
#12 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#11 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance::handle
#10 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#9 /vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Http\Middleware\HandleCors::handle
#8 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#7 /vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Http\Middleware\TrustProxies::handle
#6 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#5 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(52): Sentry\Laravel\Tracing\Middleware::handle
#4 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline::then
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel::handle
#0 /public/index.php(51): null
```

**Comment by driesvints** [comment]
Which version did you upgrade from?

**Comment by Noogic** [comment]
From 5.13.0

**Comment by driesvints** [comment]
Bit stumped as I can't see any change in 5.14.0 that could have caused this. Did you also by any chance updated laravel/framework? What version did you update from?

**Comment by Noogic** [comment]
Laravel from `v9.48.0` to `v9.50.1`

I've checked the class and it actually implements the contract, so I'm not sure how this happened. The error has only happened once.

These are some of the packages tracked by sentry
<img width="344" alt="Captura de Pantalla 2023-02-03 a las 16 35 16" src="https://user-images.githubusercontent.com/5868431/216643553-c5e3afcd-118f-4631-bc55-ac4f1ea69cf1.png">

**Comment by driesvints** [comment]
Gotcha. If it's alright with you I think it's best to let this slide. It could have been during an upgrade where code was changed that wasn't present yet in a previous running instance of supervisor. Stuff like this happens but only rarely. Think it's suffice to say that nothing major is broken. Should this return regularly feel free to report back.
