### ISSUE TITLE
Error while writing bytes to the server

### ISSUE THREAD

**Issue by ducxinh** [laravel/horizon#1285]
### Horizon Version

v5.16.1

### Laravel Version

9.52.9

### PHP Version

8.1.20

### Redis Driver

Predis

### Redis Version

6

### Description

I'm facing the issue "Error while writing bytes to the server at vendor/predis/predis/src/Connection/AbstractConnection.php:131 vendor/predis/predis/src/Connection/StreamConnection.php(270)".

I am experiencing an issue with Laravel, Queue, Redis, and the Predis client. I am getting the following error in my app: "Error while writing bytes to the server at vendor/predis/predis/src/Connection/AbstractConnection.php:131 vendor/predis/predis/src/Connection/StreamConnection.php(270)." 
The problem only occurs when there are no job queues for a certain period of time. 
When the error occurs, the next retries work fine. 
And if there are no job queues again after 30 minutes, the error happens again.

My detail:
OS: Centos 7
Redis: Azure Redis 6

### Full stacktrace
```
[2023-06-16 18:30:03] local.ERROR: Error while writing bytes to the server. [tcp://xxx-dev.redis.cache.windows.net:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): Error while writing bytes to the server. [tcp://xxx.redis.cache.windows.net:6379] at vendor/predis/predis/src/Connection/AbstractConnection.php:131)
[stacktrace]
#0 vendor/predis/predis/src/Connection/StreamConnection.php(273): Predis\\Connection\\AbstractConnection->onConnectionError()
#1 vendor/predis/predis/src/Connection/StreamConnection.php(370): Predis\\Connection\\StreamConnection->write()
#2 vendor/predis/predis/src/Connection/AbstractConnection.php(109): Predis\\Connection\\StreamConnection->writeRequest()
#3 vendor/predis/predis/src/Client.php(381): Predis\\Connection\\AbstractConnection->executeCommand()
#4 vendor/predis/predis/src/Client.php(336): Predis\\Client->executeCommand()
#5 vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call()
#6 vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(216): Illuminate\\Redis\\Connections\\Connection->command()
#7 vendor/laravel/horizon/src/Repositories/RedisJobRepository.php(384): Illuminate\\Redis\\Connections\\Connection->__call()
#8 vendor/laravel/horizon/src/Listeners/MarkJobAsReserved.php(36): Laravel\\Horizon\\Repositories\\RedisJobRepository->reserved()
#9 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Laravel\\Horizon\\Listeners\\MarkJobAsReserved->handle()
#10 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#11 vendor/laravel/horizon/src/RedisQueue.php(196): Illuminate\\Events\\Dispatcher->dispatch()
#12 vendor/laravel/horizon/src/RedisQueue.php(135): Laravel\\Horizon\\RedisQueue->event()
#13 vendor/laravel/framework/src/Illuminate/Support/helpers.php(306): Laravel\\Horizon\\RedisQueue->Laravel\\Horizon\\{closure}()
#14 vendor/laravel/horizon/src/RedisQueue.php(137): tap()
#15 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(342): Laravel\\Horizon\\RedisQueue->pop()
#16 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(351): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}()
#17 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(160): Illuminate\\Queue\\Worker->getNextJob()
#18 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\\Queue\\Worker->daemon()
#19 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#20 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#21 vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#23 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#24 vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#25 vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#26 vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#27 vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\\Component\\Console\\Command\\Command->run()
#28 vendor/symfony/console/Application.php(1063): Illuminate\\Console\\Command->run()
#29 vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#30 vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#31 vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#32 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#33 
artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
```

Thanks!

### Steps To Reproduce

1. Trigger a Job queue: example send mail to user.
2. Wait for 30 minutes
3. Trigger another Job queue: example send mail to user. 
4. There are an error happened
```
[2023-06-16 18:30:03] local.ERROR: Error while writing bytes to the server. [tcp://xxx-dev.redis.cache.windows.net:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): Error while writing bytes to the server. [tcp://xxx.redis.cache.windows.net:6379] at vendor/predis/predis/src/Connection/AbstractConnection.php:131)
[stacktrace]
```
But when the queue retries, It work fine

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
