### ISSUE TITLE
Predis: Error while writing bytes to the server

### ISSUE THREAD

**Issue by jcalonso** [laravel/horizon#152]
Hi,

I'm experiencing the following error after installing Horizon on my application. 
Horizon seems to work fine and my jobs are being queued in redis and processed correctly.
I'm not sure what could cause this issue, any ideas?

Thanks!

Details:
```
Laravel 5.5.4
Horizon: 1.0.3
```

Php:
```
PHP 7.1.9-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 06:17:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

```
redis-server -v
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9
```

Full stacktrace

```
[2017-09-21 15:32:29] production.ERROR: Error while writing bytes to the server. [tcp://127.0.0.1:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): Error while writing bytes to the server. [tcp://127.0.0.1:6379] at /var/www/myLaravelApp/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
[stacktrace]
#0 /var/www/myLaravelApp/vendor/predis/predis/src/Connection/StreamConnection.php(298): Predis\\Connection\\AbstractConnection->onConnectionError('Error while wri...')
#1 /var/www/myLaravelApp/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\\Connection\\StreamConnection->write('0*\\\\u0000job\\\\\";N...')
#2 /var/www/myLaravelApp/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\HashSetMultiple))
#3 /var/www/myLaravelApp/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\AbstractConnection->executeCommand(Object(Predis\\Command\\HashSetMultiple))
#4 /var/www/myLaravelApp/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\HashSetMultiple))
#5 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(96): Predis\\Client->__call('hmset', Array)
#6 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(108): Illuminate\\Redis\\Connections\\Connection->command('hmset', Array)
#7 /var/www/myLaravelApp/vendor/laravel/horizon/src/Repositories/RedisJobRepository.php(251): Illuminate\\Redis\\Connections\\Connection->__call('hmset', Array)
#8 /var/www/myLaravelApp/vendor/laravel/horizon/src/Listeners/MarkJobAsReserved.php(36): Laravel\\Horizon\\Repositories\\RedisJobRepository->reserved('redis', 'myRedisQueue', Object(Laravel\\Horizon\\JobPayload))
#9 [internal function]: Laravel\\Horizon\\Listeners\\MarkJobAsReserved->handle(Object(Laravel\\Horizon\\Events\\JobReserved))
#10 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(368): call_user_func_array(Array, Array)
#11 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Laravel\\\\Horizon...', Array)
#12 /var/www/myLaravelApp/vendor/laravel/horizon/src/RedisQueue.php(155): Illuminate\\Events\\Dispatcher->dispatch('Laravel\\\\Horizon...')
#13 /var/www/myLaravelApp/vendor/laravel/horizon/src/RedisQueue.php(94): Laravel\\Horizon\\RedisQueue->event('myRedisQueue', Object(Laravel\\Horizon\\Events\\JobReserved))
#14 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1035): Laravel\\Horizon\\RedisQueue->Laravel\\Horizon\\{closure}(Object(Illuminate\\Queue\\Jobs\\RedisJob))
#15 /var/www/myLaravelApp/vendor/laravel/horizon/src/RedisQueue.php(96): tap(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Closure))
#16 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(244): Laravel\\Horizon\\RedisQueue->pop('myRedisQueue')
#17 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(105): Illuminate\\Queue\\Worker->getNextJob(Object(Laravel\\Horizon\\RedisQueue), 'myRedisQueue')
#18 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'myRedisQueue', Object(Illuminate\\Queue\\WorkerOptions))
#19 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'myRedisQueue')
#20 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#21 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#26 /var/www/myLaravelApp/vendor/symfony/console/Command/Command.php(264): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/myLaravelApp/vendor/symfony/console/Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/myLaravelApp/vendor/symfony/console/Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/myLaravelApp/vendor/symfony/console/Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/myLaravelApp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/myLaravelApp/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"}
```

**Comment by themsaid** [comment]
Make sure your redis server memory is not consumed.

**Comment by jcalonso** [comment]
Thanks for replying @themsaid 
The `maxmemory` param is set to `0`
```
127.0.0.1:6379> INFO memory
# Memory
used_memory:24961032
used_memory_human:23.80M
used_memory_rss:12079104
used_memory_peak:26158472
used_memory_peak_human:24.95M
used_memory_lua:35840
mem_fragmentation_ratio:0.48
mem_allocator:jemalloc-3.4.1
```

```
127.0.0.1:6379> CONFIG GET maxmemory
1) "maxmemory"
2) "0"
```

Server does has some free memory:
```
free -hm
             total       used       free     shared    buffers     cached
Mem:          992M       888M       103M        17M        24M       181M
-/+ buffers/cache:       682M       310M
Swap:         4.0G       557M       3.5G
```

**Comment by pdewit** [comment]
I had some weird errors because I ran an older version of Redis. Your version seems a bit old, maybe you can try to update it?

**Comment by jcalonso** [comment]
Thanks @pdewit!, after upgrading to Redis 4 the errors stopped.

**Comment by romilgoel** [comment]
I got the resolution to the problem. So, there is a limit to ports that a application server can connect to a particular application on another machine. These ports were getting exhausted.
We increased the limit and the problem got resolved.

How we got to know about this problem ?
In php, we were getting "Cannot assign requested address" error while creating a socket (error code 99).

**Comment by mfn** [comment]
@romilgoel sounds interesting, can you share more details?

Specifically, what you did to increase the limits?

**Comment by qasimalbaqali** [comment]
@romilgoel I am also interested in how did you achieve the increase of ports and resolving the error.

**Comment by gianluccaferro** [comment]
@romilgoel how did you increase the  limits ?

**Comment by DerDu** [comment]
In my case, using persistent connections was the culprit. We have stopped using them; instead, we hold on to a singleton until the script ends, which achieves a similar result.
