### ISSUE TITLE
Jobs lists fail when there is a large payload for the jobs

### ISSUE THREAD

**Issue by Artistan** [laravel/horizon#192]
When you have a series of job that have a large payload (say 2mb each) then the recent jobs listing fails in horizon due to memory exhausted when dealing with the json.

Possible Solution:
https://github.com/laravel/horizon/pull/191

**Some project details on how this is affecting us...** 
- passing JSON through redis to be used with elasticsearch
- bulkJson for elastic is configurable, currently running at 2mb.
- loading the last 50 jobs results in fatal error due to memory exhausted.

```log
[2017-10-10 15:39:34] local.ERROR: Allowed memory size of 268435456 bytes exhausted (tried to allocate 100405248 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 268435456 bytes exhausted (tried to allocate 100405248 bytes) at /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:67)
[stacktrace]
#0 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(137): Symfony\\Component\\Debug\\Exception\\FatalErrorException->__construct()
#1 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalExceptionFromError()
#2 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#3 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(67): json_encode()
#4 /var/www/vhosts/laravel-app/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData()
#5 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Illuminate\\Http\\JsonResponse->__construct()
#6 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(709): Illuminate\\Http\\JsonResponse->__construct()
#7 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router::toResponse()
#8 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(645): Illuminate\\Routing\\Router->prepareResponse()
#9 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /var/www/vhosts/laravel-app/vendor/laravel/horizon/src/Http/Middleware/Authenticate.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#11 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Laravel\\Horizon\\Http\\Middleware\\Authenticate->handle()
#12 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/vhosts/laravel-app/app/Http/Middleware/HorizonStatus.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#14 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HorizonStatus->handle()
#15 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#17 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#18 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#20 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\VerifyCsrfToken->handle()
#21 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/vhosts/laravel-app/app/Http/Middleware/ShareMessagesFromSession.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#23 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ShareMessagesFromSession->handle()
#24 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/vhosts/laravel-app/app/Http/Middleware/ClusterStats.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#26 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ClusterStats->handle()
#27 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#29 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#32 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#33 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#35 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#38 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\EncryptCookies->handle()
#39 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#41 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(647): Illuminate\\Routing\\Pipeline->then()
#42 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRouteWithinStack()
#43 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(588): Illuminate\\Routing\\Router->runRoute()
#44 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(577): Illuminate\\Routing\\Router->dispatchToRoute()
#45 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#46 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): App\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#47 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#48 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#49 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#51 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Routing\\Pipeline->then()
#52 /var/www/vhosts/laravel-app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): App\\Http\\Kernel->sendRequestThroughRouter()
#53 /var/www/vhosts/laravel-app/public/index.php(54): App\\Http\\Kernel->handle()
#54 /var/www/vhosts/laravel-app/public/index.php(0): {main}()
#55 {main}
"}
```

**Comment by Artistan** [comment]
Why closed?

**Comment by themsaid** [comment]
Pr is already under discussion
