### ISSUE TITLE
Call to undefined method Illuminate\Queue\DatabaseQueue::readyNow()

### ISSUE THREAD

**Issue by skatetdieu** [laravel/horizon#351]
Hello, I'm trying to use the [database](https://laravel.com/docs/5.5/queues#driver-prerequisites) as the `QUEUE_DRIVER` and connection in horizon.php for my supervisor. 

I am getting the following error:

```php
Call to undefined method Illuminate\Queue\DatabaseQueue::readyNow() 
    "exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): 
    Call to undefined method Illuminate\\Queue\\DatabaseQueue::readyNow() at /vagrant/vendor/laravel/horizon/src/AutoScaler.php:80)
```

I looked at the code and there is no `readyNow` method in DatabaseQueue but I don't know if I am missing something.

If I change the settings to use Redis instead it works just fine.

Any help is appreciated!

Thanks!

Full stack trace of the error:

```php
Call to undefined method Illuminate\Queue\DatabaseQueue::readyNow() {
"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Illuminate\\Queue\\DatabaseQueue::readyNow() at /vagrant/vendor/laravel/horizon/src/AutoScaler.php:80)
[stacktrace]
#0 /vagrant/vendor/laravel/framework/src/Illuminate/Support/Collection.php(928): Laravel\\Horizon\\AutoScaler->Laravel\\Horizon\\{closure}(Object(Laravel\\Horizon\\ProcessPool), 'default')
#1 /vagrant/vendor/laravel/horizon/src/AutoScaler.php(83): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#2 /vagrant/vendor/laravel/horizon/src/AutoScaler.php(49): Laravel\\Horizon\\AutoScaler->timeToClearPerQueue(Object(Laravel\\Horizon\\Supervisor), Object(Illuminate\\Support\\Collection))
#3 /vagrant/vendor/laravel/horizon/src/Supervisor.php(325): Laravel\\Horizon\\AutoScaler->scale(Object(Laravel\\Horizon\\Supervisor))
#4 /vagrant/vendor/laravel/horizon/src/Supervisor.php(282): Laravel\\Horizon\\Supervisor->autoScale()
#5 /vagrant/vendor/laravel/horizon/src/Supervisor.php(251): Laravel\\Horizon\\Supervisor->loop()
#6 /vagrant/vendor/laravel/horizon/src/Console/SupervisorCommand.php(86): Laravel\\Horizon\\Supervisor->monitor()
#7 /vagrant/vendor/laravel/horizon/src/Console/SupervisorCommand.php(65): Laravel\\Horizon\\Console\\SupervisorCommand->start(Object(Laravel\\Horizon\\Supervisor))
#8 [internal function]: Laravel\\Horizon\\Console\\SupervisorCommand->handle()
#9 /vagrant/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /vagrant/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /vagrant/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#14 /vagrant/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /vagrant/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /vagrant/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /vagrant/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SupervisorCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /vagrant/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /vagrant/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /vagrant/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
```

**Comment by drbyte** [comment]
> Hello, I'm trying to use the database as the QUEUE_DRIVER and connection in horizon.php 

Horizon is specifically designed for **Redis**. See the README and the [Docs](https://laravel.com/docs/horizon):

> Horizon provides a beautiful dashboard and code-driven configuration for your Laravel powered **Redis queues**.

**Comment by skatetdieu** [comment]
Thanks @drbyte. So sad it doesn't work for database queues.
