### ISSUE TITLE
Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, integer 

### ISSUE THREAD

**Issue by ihsanberahim** [laravel/horizon#352]
```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, integer given, called in /app/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php on line 50
at Laravel\Horizon\Repositories\RedisSupervisorRepository->all (/app/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php:70)
at Laravel\Horizon\Repositories\RedisSupervisorRepository->longestActiveTimeout (/app/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php:99)
at Laravel\Horizon\MasterSupervisor->terminate (/app/vendor/laravel/horizon/src/MasterSupervisor.php:163)
at Laravel\Horizon\MasterSupervisor->Laravel\Horizon\{closure} (/app/vendor/laravel/horizon/src/MasterSupervisor.php:291)
at Predis\Connection\StreamConnection->read (/app/vendor/predis/predis/src/Connection/StreamConnection.php:311)
at Predis\Connection\AbstractConnection->readResponse (/app/vendor/predis/predis/src/Connection/AbstractConnection.php:120)
at Predis\Pipeline\Pipeline->executePipeline (/app/vendor/predis/predis/src/Pipeline/Pipeline.php:141)
at Predis\Pipeline\Pipeline->flushPipeline (/app/vendor/predis/predis/src/Pipeline/Pipeline.php:165)
at Predis\Pipeline\Pipeline->execute (/app/vendor/predis/predis/src/Pipeline/Pipeline.php:214)
at Predis\Client->createPipeline (/app/vendor/predis/predis/src/Client.php:445)
at Predis\Client->sharedContextFactory (/app/vendor/predis/predis/src/Client.php:396)
at Predis\Client->pipeline (/app/vendor/predis/predis/src/Client.php:418)
at Illuminate\Redis\Connections\Connection->command (/app/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:96)
at Illuminate\Redis\Connections\Connection->__call (/app/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:108)
at Laravel\Horizon\Repositories\RedisMasterSupervisorRepository->update (/app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php:116)
at Laravel\Horizon\MasterSupervisor->persist (/app/vendor/laravel/horizon/src/MasterSupervisor.php:278)
at Laravel\Horizon\MasterSupervisor->loop (/app/vendor/laravel/horizon/src/MasterSupervisor.php:237)
at Laravel\Horizon\MasterSupervisor->monitor (/app/vendor/laravel/horizon/src/MasterSupervisor.php:206)
at Laravel\Horizon\Console\HorizonCommand->handle (/app/vendor/laravel/horizon/src/Console/HorizonCommand.php:64)
at call_user_func_array ([internal function])
at Illuminate\Container\BoundMethod::Illuminate\Container\{closure} (/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29)
at Illuminate\Container\BoundMethod::callBoundMethod (/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87)
at Illuminate\Container\BoundMethod::call (/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31)
at Illuminate\Container\Container->call (/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:564)
at Illuminate\Console\Command->execute (/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:184)
at Symfony\Component\Console\Command\Command->run (/app/vendor/symfony/console/Command/Command.php:251)
at Illuminate\Console\Command->run (/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:171)
at Symfony\Component\Console\Application->doRunCommand (/app/vendor/symfony/console/Application.php:886)
at Symfony\Component\Console\Application->doRun (/app/vendor/symfony/console/Application.php:262)
at Symfony\Component\Console\Application->run (/app/vendor/symfony/console/Application.php:145)
at Illuminate\Console\Application->run (/app/vendor/laravel/framework/src/Illuminate/Console/Application.php:89)
at Illuminate\Foundation\Console\Kernel->handle (/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122)
at {main} (/app/artisan:37)
```

This error appear in my app running in GoogleAppEngine. 

Not sure yet how to reproduce and give any details.

**Comment by adamtester** [comment]
I just got the same thing a few times, but on integer and one object?

```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, integer given, called in /home/forge/jupiter.belldm.local/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php on line 50
#20 vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(70): get
#19 vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(50): all
#18 vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(99): longestActiveTimeout
#17 vendor/laravel/horizon/src/MasterSupervisor.php(163): terminate
#16 vendor/laravel/horizon/src/MasterSupervisor.php(291): Laravel\Horizon\{closure}
#15 vendor/laravel/horizon/src/MasterSupervisor.php(206): monitor
#14 vendor/laravel/horizon/src/Console/HorizonCommand.php(64): handle
#13 vendor/laravel/horizon/src/Console/HorizonCommand.php(0): call_user_func_array
#12 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\{closure}
#11 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): callBoundMethod
#10 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): call
#9 vendor/laravel/framework/src/Illuminate/Container/Container.php(549): call
#8 vendor/laravel/framework/src/Illuminate/Console/Command.php(183): execute
#7 vendor/symfony/console/Command/Command.php(252): run
#6 vendor/laravel/framework/src/Illuminate/Console/Command.php(170): run
#5 vendor/symfony/console/Application.php(946): doRunCommand
#4 vendor/symfony/console/Application.php(248): doRun
#3 vendor/symfony/console/Application.php(148): run
#2 vendor/laravel/framework/src/Illuminate/Console/Application.php(88): run
#1 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): handle
#0 artisan(35): null
```

```
Type error: Argument 1 passed to Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, integer given
```

```
Type error: Argument 1 passed to Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, object given
```

I'm looking into it and will report back with more info

**Comment by ihsanberahim** [comment]
This not happen anymore after i upgrade my redis.

**Comment by glamorous** [comment]
From which version to which version did you upgrade?

**Comment by ihsanberahim** [comment]
@glamorous the upgrade means i implement high availability redis server in GoogleCloudPlatform.

**Comment by huqian1984** [comment]
> @glamorous the upgrade means i implement high availability redis server in GoogleCloudPlatform.

Happened in AliCloud too...
