### ISSUE TITLE
Frequent errors from Predis saying "Error while reading line from the server"

### ISSUE THREAD

**Issue by srottem** [laravel/horizon#366]
Since moving from using the basic Laravel queue worker to Horizon I've started seeing frequent error messages in my log files when processing queued jobs.  The error happens more frequently the more jobs are processed and appears to be Horizon related.

```
Predis\Connection\ConnectionException: Error while reading line from the server. [tcp://127.0.0.1:6379]
#34 vendor/predis/predis/src/Connection/AbstractConnection.php(155): onConnectionError
#33 vendor/predis/predis/src/Connection/StreamConnection.php(314): read
#32 vendor/predis/predis/src/Connection/AbstractConnection.php(120): readResponse
#31 vendor/predis/predis/src/Connection/AbstractConnection.php(112): executeCommand
#30 vendor/predis/predis/src/Client.php(331): executeCommand
#29 vendor/predis/predis/src/Client.php(314): __call
#28 vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(96): command
#27 vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(108): __call
#26 vendor/laravel/horizon/src/Repositories/RedisJobRepository.php(271): reserved
#25 vendor/laravel/horizon/src/Listeners/MarkJobAsReserved.php(36): handle
#24 vendor/laravel/horizon/src/Listeners/MarkJobAsReserved.php(0): call_user_func_array
#23 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(379): Illuminate\Events\{closure}
#22 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): dispatch
#21 vendor/laravel/horizon/src/RedisQueue.php(155): event
#20 vendor/laravel/horizon/src/RedisQueue.php(94): Laravel\Horizon\{closure}
#19 vendor/laravel/framework/src/Illuminate/Support/helpers.php(1041): tap
#18 vendor/laravel/horizon/src/RedisQueue.php(96): pop
#17 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(246): getNextJob
#16 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(107): daemon
#15 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): runWorker
#14 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): handle
#13 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(0): call_user_func_array
#12 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\{closure}
#11 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): callBoundMethod
#10 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): call
#9 vendor/laravel/framework/src/Illuminate/Container/Container.php(564): call
#8 vendor/laravel/framework/src/Illuminate/Console/Command.php(184): execute
#7 vendor/symfony/console/Command/Command.php(251): run
#6 vendor/laravel/framework/src/Illuminate/Console/Command.php(171): run
#5 vendor/symfony/console/Application.php(886): doRunCommand
#4 vendor/symfony/console/Application.php(262): doRun
#3 vendor/symfony/console/Application.php(145): run
#2 vendor/laravel/framework/src/Illuminate/Console/Application.php(89): run
#1 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): handle
#0 artisan(37): null
```
Any thoughts?

**Comment by iShotFT** [comment]
I'm having the same issue

**Comment by robclancy** [comment]
I've had this since horizon was released. I just ignore it. Would be nice to know why it is happening.

**Comment by WillemRoman** [comment]
Same issue here. Did not manage to solve it yet. Would be awesome if somebody has a solution.

**Comment by srottem** [comment]
Thanks iShotFT - good feedback.  I would have preferred not to have to install phpredis but it sounds like it's the only fix available for now.

**Comment by robclancy** [comment]
I don't want to change entire package for this but I guess I need to eventually. Annoying.

**Comment by driesvints** [comment]
Hey everyone. Thanks for reporting this. I believe this might be related to https://github.com/laravel/framework/issues/25039 so I don't think it's Horizon specific. Let's continue the discussion on the that issue. Feel free to reply back if you want to provide some additional feedback.

**Comment by srottem** [comment]
Yeah, I pulled Horizon from my project because of the errors, but it turns out they're still showing up.

**Comment by eithed** [comment]
Given that https://github.com/laravel/framework/issues/25039 was just closed, can you please reopen this.

**Comment by driesvints** [comment]
@eithed like Taylor says: you'd need a cache failover system which is a feature request and should be implemented in Laravel itself.
