### ISSUE TITLE
My sentry is reporting 'The provided cwd does not exist'

### ISSUE THREAD

**Issue by santigarcor** [laravel/horizon#403]
I'm user Laravel 5.7.9 and horizon 1.4.0.

My sentry started reporting this weird error `The provided cwd does not exist.` and I don't know what it is, I haven't changed anything in the code this is the stacktrace sentry shows me:

```
Symfony\Component\Process\Exception\RuntimeException: The provided cwd does not exist.
#28 vendor/symfony/process/Process.php(301): start
#27 vendor/laravel/horizon/src/WorkerProcess.php(57): start
#26 vendor/laravel/horizon/src/WorkerProcess.php(111): restart
#25 vendor/laravel/horizon/src/WorkerProcess.php(97): monitor
#24 vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Illuminate\Support\{closure}
#23 vendor/laravel/framework/src/Illuminate/Support/Collection.php(407): each
#22 vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): __call
#21 vendor/laravel/horizon/src/ProcessPool.php(190): monitor
#20 vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Illuminate\Support\{closure}
#19 vendor/laravel/framework/src/Illuminate/Support/Collection.php(407): each
#18 vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): __call
#17 vendor/laravel/horizon/src/Supervisor.php(284): loop
#16 vendor/laravel/horizon/src/Supervisor.php(251): monitor
#15 vendor/laravel/horizon/src/Console/SupervisorCommand.php(86): start
#14 vendor/laravel/horizon/src/Console/SupervisorCommand.php(65): handle
#13 vendor/laravel/horizon/src/Console/SupervisorCommand.php(0): call_user_func_array
#12 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\{closure}
#11 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): callBoundMethod
#10 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): call
#9 vendor/laravel/framework/src/Illuminate/Container/Container.php(564): call
#8 vendor/laravel/framework/src/Illuminate/Console/Command.php(183): execute
#7 vendor/symfony/console/Command/Command.php(251): run
#6 vendor/laravel/framework/src/Illuminate/Console/Command.php(170): run
#5 vendor/symfony/console/Application.php(886): doRunCommand
#4 vendor/symfony/console/Application.php(262): doRun
#3 vendor/symfony/console/Application.php(145): run
#2 vendor/laravel/framework/src/Illuminate/Console/Application.php(89): run
#1 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): handle
#0 artisan(37): null
```

It shows after I type horizon:terminate, horizon:purge and i think also when the supervisor tried to start a new process.

Could you please help me, i don't know what to do now.

**Comment by mfn** [comment]
`cwd` is the "current working directory".

My first guess would be: it's a problem with the filesystem and unrelated to horizon.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a Horizon bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by jpswade** [comment]
@santigarcor did you ever figure out what the issue was?
