### ISSUE TITLE
Old horizon backoffice tab triggering 

### ISSUE THREAD

**Issue by frinux** [laravel/horizon#521]
I let an opened tab of horizon backoffice during the night. Of course authentication expired, but it seems it is not handled properly: my application logged continuously an obscure error:

```
[2019-02-26 09:04:26] production.ERROR: [5df10914-056a-42d4-8dbc-cbff20e61890] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:29] production.ERROR: [36501156-a817-4fe9-9c4c-3035ef612f89] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:31] production.ERROR: [19455bf2-7169-4040-8070-cf7abf7cef98] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:35] production.ERROR: [11db6431-2a57-41a5-b671-7dfc5c6d753c] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:37] production.ERROR: [5dd76082-4128-49ed-8206-733651f5fd7b] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:40] production.ERROR: [593d5869-0ddf-4150-a093-eafcb6cc3f15] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:43] production.ERROR: [7131c9c8-bab5-46ea-8532-f1ff1bd2b289] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:47] production.ERROR: [dd7610b6-9cd8-4249-a616-01da7523542d] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943 
[2019-02-26 09:04:50] production.ERROR: [fc14d868-3aa2-4816-a438-b2af2b68159a] /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:943
```

When debugging, the stacktrace showed:

```
[2019-02-26 09:00:40] production.ERROR: [845ba0a9-0462-47cf-8190-67bc2fe7b8d7] 
#0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(46): Illuminate\Foundation\Application->abort(403, '', Array) 
#1 /var/www/laravel/vendor/laravel/horizon/src/Http/Middleware/Authenticate.php(18): abort(403) 
#2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\Horizon\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure)) 
```

Failed authentication should be handled properly: don't trigger ERROR level logs.
Frontend should not retry every second to re-authenticate if 403 is returned.

**Comment by driesvints** [comment]
Hmm. Indeed. We could handle this better.

**Comment by driesvints** [comment]
I've looked at this but have a few questions. Normally, `HttpException` aren't reported. Can you copy/paste your exception handler class? Can you also tell me which horizon and laravel version you're using?

**Comment by driesvints** [comment]
> Frontend should not retry every second to re-authenticate if 403 is returned.

This is simply the current way Horizon re-polls for new results. You could argue that a system could be implemented to show an "unauthenticated" error instead perhaps. This might be a good feature. Can you create a separate issue for this?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
