### ISSUE TITLE
Class 'Redis' not found

### ISSUE THREAD

**Issue by mitoop** [laravel/horizon#595]
- Horizon Version: 3.1.2
- Laravel Version: 5.8.16
- PHP Version: 7.3.5
- Redis Driver & Version: phpredis 4.3.0
- Database Driver & Version: Mysql 8.0.16

### Description:
horizon works well, but `horizon:snapshot` report `Class 'Redis' not found` every five minutes in laravel log file.  I found that in my **Mac dev envionment,** it report the error, but in the Linux environment, `horizon:snapshot` works well and no errors found.

```

[2019-05-17 14:20:00] local.ERROR: Class 'Redis' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Redis' not found at /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:65)
[stacktrace]
#0 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(23): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#1 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(98): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#2 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(79): Illuminate\\Redis\\RedisManager->resolve('horizon')
#3 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(93): Illuminate\\Redis\\RedisManager->connection('horizon')
#4 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(66): Laravel\\Horizon\\Lock->connection()
#5 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Console/SnapshotCommand.php(34): Laravel\\Horizon\\Lock->get('metrics:snapsho...', 300)
#6 [internal function]: Laravel\\Horizon\\Console\\SnapshotCommand->handle(Object(Laravel\\Horizon\\Lock), Object(Laravel\\Horizon\\Repositories\\RedisMetricsRepository))
#7 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#12 /Users/mitoop/Sites/joax/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SnapshotCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/mitoop/Sites/joax/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"} 
[2019-05-17 14:25:01] local.ERROR: Class 'Redis' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Redis' not found at /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:65)
[stacktrace]
#0 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(23): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#1 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(98): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#2 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(79): Illuminate\\Redis\\RedisManager->resolve('horizon')
#3 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(93): Illuminate\\Redis\\RedisManager->connection('horizon')
#4 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(66): Laravel\\Horizon\\Lock->connection()
#5 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Console/SnapshotCommand.php(34): Laravel\\Horizon\\Lock->get('metrics:snapsho...', 300)
#6 [internal function]: Laravel\\Horizon\\Console\\SnapshotCommand->handle(Object(Laravel\\Horizon\\Lock), Object(Laravel\\Horizon\\Repositories\\RedisMetricsRepository))
#7 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#12 /Users/mitoop/Sites/joax/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SnapshotCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/mitoop/Sites/joax/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"} 
[2019-05-17 14:30:00] local.ERROR: Class 'Redis' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Redis' not found at /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:65)
[stacktrace]
#0 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(23): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#1 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(98): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#2 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(79): Illuminate\\Redis\\RedisManager->resolve('horizon')
#3 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(93): Illuminate\\Redis\\RedisManager->connection('horizon')
#4 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(66): Laravel\\Horizon\\Lock->connection()
#5 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Console/SnapshotCommand.php(34): Laravel\\Horizon\\Lock->get('metrics:snapsho...', 300)
#6 [internal function]: Laravel\\Horizon\\Console\\SnapshotCommand->handle(Object(Laravel\\Horizon\\Lock), Object(Laravel\\Horizon\\Repositories\\RedisMetricsRepository))
#7 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#12 /Users/mitoop/Sites/joax/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SnapshotCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/mitoop/Sites/joax/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"} 
[2019-05-17 14:35:01] local.ERROR: Class 'Redis' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Redis' not found at /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:65)
[stacktrace]
#0 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(23): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#1 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(98): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#2 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(79): Illuminate\\Redis\\RedisManager->resolve('horizon')
#3 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(93): Illuminate\\Redis\\RedisManager->connection('horizon')
#4 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(66): Laravel\\Horizon\\Lock->connection()
#5 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Console/SnapshotCommand.php(34): Laravel\\Horizon\\Lock->get('metrics:snapsho...', 300)
#6 [internal function]: Laravel\\Horizon\\Console\\SnapshotCommand->handle(Object(Laravel\\Horizon\\Lock), Object(Laravel\\Horizon\\Repositories\\RedisMetricsRepository))
#7 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#12 /Users/mitoop/Sites/joax/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SnapshotCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/mitoop/Sites/joax/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"} 
[2019-05-17 14:40:01] local.ERROR: Class 'Redis' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Redis' not found at /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:65)
[stacktrace]
#0 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(23): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#1 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(98): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#2 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(79): Illuminate\\Redis\\RedisManager->resolve('horizon')
#3 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(93): Illuminate\\Redis\\RedisManager->connection('horizon')
#4 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Lock.php(66): Laravel\\Horizon\\Lock->connection()
#5 /Users/mitoop/Sites/joax/vendor/laravel/horizon/src/Console/SnapshotCommand.php(34): Laravel\\Horizon\\Lock->get('metrics:snapsho...', 300)
#6 [internal function]: Laravel\\Horizon\\Console\\SnapshotCommand->handle(Object(Laravel\\Horizon\\Lock), Object(Laravel\\Horizon\\Repositories\\RedisMetricsRepository))
#7 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#12 /Users/mitoop/Sites/joax/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SnapshotCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /Users/mitoop/Sites/joax/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/mitoop/Sites/joax/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/mitoop/Sites/joax/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"} 

```
### Steps To Reproduce:
when set 
```
/**
 * Define the application's command schedule.
 *
 * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
 * @return void
 */
protected function schedule(Schedule $schedule)
{
    $schedule->command('horizon:snapshot')->everyFiveMinutes();
}
```
in the application's scheduler.

**Comment by mitoop** [comment]
I found that in my crontab file
``` 
* * * * * cd /Users/mitoop/Sites/joax && php artisan schedule:run >> /dev/null 2>&1
```
the php link another php, and it does have not the redis extension. when I replace php with absolute php link, it works well.

**Comment by vesper8** [comment]
Thank you for this @mitoop, it was driving me mad. I had set my cron jobs to use /usr/bin/php and that was an old version (PHP 7.1). The brew installed version is set to /usr/local/bin/php. It was using this older version and yadda yadda.. I had the exact same issue as you described

**Comment by krunikasheth114** [comment]
horizon works well, but horizon:snapshot report Class 'Redis' not found every five minutes in laravel log file. I found that in my Mac dev envionment, it report the error, but in the Linux environment, horizon:snapshot works well and no errors found.

how can i solve this error in windows
