### ISSUE TITLE
Can't retry failed jobs

### ISSUE THREAD

**Issue by curious-jim** [laravel/horizon#604]
- Horizon Version: 3.2.1
- Laravel Version: 5.8.19
- PHP Version: 7.3.5
- Redis Driver & Version: predis/phpredis 4.0.9 & 1.1.1
- Database Driver & Version: Ver 15.1 Distrib 10.3.15-MariaDB

### Description:

```
$ php artisan queue:retry all

In Tags.php line 107:
  Class  does not exist
```

trace:

```
local.ERROR: Class  does not exist {"exception":"[object] (ReflectionException(code: -1): Class  does not exist at /home/dev/app/vendor/laravel/horizon/src/Tags.php:107)
[stacktrace]
#0 /home/dev/app/vendor/laravel/horizon/src/Tags.php(107): ReflectionClass->__construct('')
#1 /home/dev/app/vendor/laravel/horizon/src/Tags.php(28): Laravel\\Horizon\\Tags::modelsFor(Array)
#2 /home/dev/app/vendor/laravel/horizon/src/JobPayload.php(132): Laravel\\Horizon\\Tags::for(NULL)
#3 /home/dev/app/vendor/laravel/horizon/src/JobPayload.php(91): Laravel\\Horizon\\JobPayload->determineTags(NULL)
#4 /home/dev/app/vendor/laravel/horizon/src/RedisQueue.php(59): Laravel\\Horizon\\JobPayload->prepare(NULL)
#5 /home/dev/app/vendor/laravel/framework/src/Illuminate/Queue/Console/RetryCommand.php(71): Laravel\\Horizon\\RedisQueue->pushRaw('{\"timeout\":null...', 'production')
#6 /home/dev/app/vendor/laravel/framework/src/Illuminate/Queue/Console/RetryCommand.php(37): Illuminate\\Queue\\Console\\RetryCommand->retryJob(Object(stdClass))
#7 [internal function]: Illuminate\\Queue\\Console\\RetryCommand->handle()
#8 /home/dev/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /home/dev/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/dev/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /home/dev/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /home/dev/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#13 /home/dev/app/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /home/dev/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /home/dev/app/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /home/dev/app/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\RetryCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /home/dev/app/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /home/dev/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /home/dev/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /home/dev/app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
```

in RedisQueue@pushRaw in `$payload = (new JobPayload($payload))->prepare($this->lastPushed)->value;` the `$this->lastPushed` is null

### Steps To Reproduce:

`php artisan queue:retry all`

**Comment by driesvints** [comment]
Can you please provide a repo with a minimum amount of setup that reproduces this problem? Some people have submitted this before but this was always a specific use-case and there wasn't a way to reproduce it.

**Comment by curious-jim** [comment]
Can't reproduce it with the fresh installation, can't even figure out what is causing the error in my live app. Only some jobs are affected. I'll run more tests when I'll have more time

**Comment by driesvints** [comment]
Okay, feel free to respond back when you have more info.

**Comment by usamamuneerchaudhary** [comment]
Facing the similar issue on Laravel 7.14, horizon 4.3 using PostgreSQL.

**Comment by minkbear** [comment]
Facing the same issue in Laravel 7.12, horizon 4.3.3 with mysql

**Comment by minkbear** [comment]
Found that payload no tags.
So add below on https://github.com/laravel/horizon/blob/a37c6d7526848419d963df2fc14f4120a76a4e7d/src/JobPayload.php#L126-L133

```
case !array_key_exists('tags', $this->decoded):
return [];
```

Then $ php artisan queue:retry all work fine.

I don't know why payload no tags
