### ISSUE TITLE
redis cluster queue error

### ISSUE THREAD

**Issue by gedongdong** [laravel/horizon#913]
- Horizon Version: 3.7.2
- Laravel Version: 6.2
- PHP Version: 7.2.21
- Redis Driver & Version: predis 1.1.1
- Database Driver & Version: mysql 8.0

### Description:
config/database.php
![image](https://user-images.githubusercontent.com/13677866/96720929-03104f00-13de-11eb-8719-17162b5738c5.png)

config/queue.php
![image](https://user-images.githubusercontent.com/13677866/96721043-2affb280-13de-11eb-9270-5f16beef7858.png)

config/horizon.php
![image](https://user-images.githubusercontent.com/13677866/96721095-3e128280-13de-11eb-9e04-bab0d58b315d.png)

errinfo:
```
[2020-10-21 20:31:52] production.ERROR: CROSSSLOT Keys in request don't hash to the same slot {"exception":"[object] (Predis\\Response\\ServerException(code: 0): CROSSSLOT Keys in request don't hash to the same slot at /home/test/account.sso.redis.monitor/vendor/predis/predis/src/Client.php:370)
[stacktrace]
#0 /home/test/account.sso.redis.monitor/vendor/predis/predis/src/Client.php(335): Predis\\Client->onErrorResponse(Object(Predis\\Command\\ServerEval), Object(Predis\\Response\\Error))
#1 /home/test/account.sso.redis.monitor/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\ServerEval))
#2 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call('eval', Array)
#3 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\Connection->command('eval', Array)
#4 /home/test/account.sso.redis.monitor/vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(200): Illuminate\\Redis\\Connections\\Connection->__call('eval', Array)
#5 /home/test/account.sso.redis.monitor/vendor/laravel/horizon/src/Listeners/UpdateJobMetrics.php(53): Laravel\\Horizon\\Repositories\\RedisMetricsRepository->incrementQueue('{ssolog1}', 16.13)
#6 [internal function]: Laravel\\Horizon\\Listeners\\UpdateJobMetrics->handle(Object(Laravel\\Horizon\\Events\\JobDeleted))
#7 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(388): call_user_func_array(Array, Array)
#8 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Laravel\\\\Horizon...', Array)
#9 /home/test/account.sso.redis.monitor/vendor/laravel/horizon/src/RedisQueue.php(155): Illuminate\\Events\\Dispatcher->dispatch('Laravel\\\\Horizon...')
#10 /home/test/account.sso.redis.monitor/vendor/laravel/horizon/src/RedisQueue.php(124): Laravel\\Horizon\\RedisQueue->event('{ssolog1}', Object(Laravel\\Horizon\\Events\\JobDeleted))
#11 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(84): Laravel\\Horizon\\RedisQueue->deleteReserved('{ssolog1}', Object(Illuminate\\Queue\\Jobs\\RedisJob))
#12 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(66): Illuminate\\Queue\\Jobs\\RedisJob->delete()
#13 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#14 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\\Queue\\Jobs\\Job->fire()
#15 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#16 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#17 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', '{ssolog1}', Object(Illuminate\\Queue\\WorkerOptions))
#18 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', '{ssolog1}')
#19 /home/test/account.sso.redis.monitor/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#20 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#21 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#22 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#24 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#25 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#26 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#27 /home/test/account.sso.redis.monitor/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 /home/test/account.sso.redis.monitor/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /home/test/account.sso.redis.monitor/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand),Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /home/test/account.sso.redis.monitor/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput),Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /home/test/account.sso.redis.monitor/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /home/test/account.sso.redis.monitor/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 {main}
"}
```

horizon command：
![image](https://user-images.githubusercontent.com/13677866/96721417-ae210880-13de-11eb-863c-8759123a515c.png)

### Steps To Reproduce:
The redis cluster has 6 nodes and a virtual ip。
The queue task is successful, but there will be an exception message。

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by miaotiao** [comment]
@gedongdong 这是由于 redis 集群 hash slot 问题导致，你可以设置 `HORIZON_PREFIX` 带有一个 hash tag 就行。例如： "{laravel_horizon}:"

**Comment by amos-yau** [comment]
@miaotiao 成功解決了我的問題，感謝！你怎麼會知道這密技，想請教一下是redis cluster就必須使用 {xxx}: 嗎？

**Comment by miaotiao** [comment]
@amos-yau 是必须使用的。具体原因当时很明白，但是现在有点模糊了。大致是在 redis cluster 模式下，job 会由于该模式下的 hash slot 被分配到不同 redis 节点上。但是由于 horizon 使用了 lua 脚本来保证多条指令一并执行的原子性，lua 脚本并不能在多节点的情况下执行成功，所以就使用 hash tags 来保证所有的 job 在一个 slot 内（也就是一个节点上），就一切 ok 了。

最后： 秘技 = 不断排查跟踪错误 + google
