### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by danijelk** [laravel/horizon#922]
- Horizon Version: 5.3
- Laravel Version: 8.12.3
- PHP Version: 7.4.11

We have started to see increase in errors for duplicate uuid keys for some reason, can't pinpoint why it would have the same uuid this many times

<img width="925" alt="Screen Shot 2020-11-07 at 14 58 53" src="https://user-images.githubusercontent.com/580753/98443148-c3e63b80-2109-11eb-9beb-ee083b869211.png">

`
[2020-11-07 13:20:23] production.WARNING: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3e2e41b5-2b0c-4a49-a96d-a6c4f3b24890' for key 'failed_jobs_uuid_unique' (SQL: insert into `failed_jobs` (`uuid`, `connection`, `queue`, `payload`, `exception`, `failed_at`) values (3e2e41b5-2b0c-4a49-a96d-a6c4f3b24890, redis, default, {"uuid":"3e2e41b5-2b0c-4a49-a96d-a6c4f3b24890","displayName":"App\\Jobs\\SendMqttMessage"`
```


 Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\SendMqttMessage has been attempted too many times or run too long. The job may have previously timed out. in /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:713
Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(195): Illuminate\Queue\Worker->maxAttemptsExceededException()
#1 /app/vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php(150): Illuminate\Queue\Worker->Illuminate\Queue\{closure}()
#2 /app/vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php(126): Salman\Mqtt\MqttClass\MqttService->read()
#3 /app/vendor/salmanzafar/laravel-mqtt/src/MqttClass/Mqtt.php(79): Salman\Mqtt\MqttClass\MqttService->connect()
#4 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Salman\Mqtt\MqttClass\Mqtt->ConnectAndPublish()
#5 /app/app/Jobs/SendMqttMessage.php(31): Illuminate\Support\Facades\Facade::__callStatic()
#6 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\SendMqttMessage->handle()
#7 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#9 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#10 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#11 /app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#12 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#13 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#15 /app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Bus\Dispatcher->dispatchNow()
#16 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#17 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(87): Illuminate\Pipeline\Pipeline->then()
#19 /app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(60): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#20 /app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#21 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\Queue\Jobs\Job->fire()
#22 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process()
#23 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob()
#24 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon()
#25 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker()
#26 /app/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\Queue\Console\WorkCommand->handle()
#27 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#28 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#29 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#30 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#31 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#32 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#33 /app/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute()
#34 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#35 /app/vendor/symfony/console/Application.php(920): Illuminate\Console\Command->run()
#36 /app/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#37 /app/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#38 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#39 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#40 /app/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#41 {main}, 2020-11-07 13:20:23)) 
```

**Comment by driesvints** [comment]
Hmm odd. Can you post the code for `SendMqttMessage` please? It seems like for some reason the same job is added to the failed jobs table multiple times. Could be related to retrying although that should cause the duplicate UUID.

**Comment by danijelk** [comment]
You bet
```

<?php

namespace App\Jobs;

use Exception;
use Illuminate\Bus\Queueable;
use Salman\Mqtt\Facades\Mqtt;
use Illuminate\Support\Facades\Log;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

class SendMqttMessage implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable;

    private $topic;
    private $message;
    private $clientId;

    public function __construct($topic, $message, $clientId = null)
    {
        $this->topic = $topic;
        $this->message = $message;
        $this->clientId = $clientId;
    }

    public function handle(): void
    {
        try {
            Mqtt::ConnectAndPublish($this->topic, $this->message, $this->clientId);
        } catch (Exception $exception) {
            Log::warning($exception->getMessage());
        }
    }
}

```

**Comment by driesvints** [comment]
Isn't the problem that you're not re-throwing the exception?

**Comment by themsaid** [comment]
Make sure the job isn't getting picked by multiple workers. Ensure the `retry_after` configuration is longer than the job timeout.

**Comment by danijelk** [comment]
> Isn't the problem that you're not re-throwing the exception?

Don't think so? Other jobs that fail do not even have a try catch.

> Make sure the job isn't getting picked by multiple workers. Ensure the `retry_after` configuration is longer than the job timeout.

Now we're on to something, we did remove the retry_after, which I see is then defaulted to 60s. We also have long lasting jobs +10min which does indeed give issues in current setup. Will have to rethink our long lasting jobs like start a new horizon pod with the retry_after set to a very high number.

Would love to be able to set the timeout(s) per job, so that our long-lasting jobs do not run into the retry_after. Will give it a bump and see if that helps.

**Comment by themsaid** [comment]
Use a different connection with longer `retry_after` for jobs that need to run so long.

So your issue here is the job gets picked by multiple workers because the `retry_after` is too short.
