### ISSUE TITLE
Error in laravel.log - read error on connection to 127.0.0.1:6379

### ISSUE THREAD

**Issue by stu177** [laravel/horizon#934]
- Horizon Version: 5.4.0
- Laravel Version: 8.10.0
- PHP Version: 7.4.11
- Redis Driver & Version: phpredis 5.3.2
- Database Driver & Version: MySQL 5.7 

### Description:

Every 10 minutes or so I'm getting the following error in `laravel.log`:

````
[2020-11-25 16:41:03] staging.ERROR: read error on connection to 127.0.0.1:6379 {"userId":1,"exception":"[object] (RedisException(code: 0): read error on connection to 127.0.0.1:6379 at /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:421)
[stacktrace]
#0 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(421): Redis->exec()
#1 /home/example/www/staging/releases/119/vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(317): Illuminate\\Redis\\Connections\\PhpRedisConnection->transaction()
#2 /home/example/www/staging/releases/119/vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(266): Laravel\\Horizon\\Repositories\\RedisMetricsRepository->baseSnapshotData()
#3 /home/example/www/staging/releases/119/vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(248): Laravel\\Horizon\\Repositories\\RedisMetricsRepository->storeSnapshotForJob()
#4 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(230): Laravel\\Horizon\\Repositories\\RedisMetricsRepository->Laravel\\Horizon\\Repositories\\{closure}()
#5 /home/example/www/staging/releases/119/vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(249): Illuminate\\Support\\Collection->each()
#6 /home/example/www/staging/releases/119/vendor/laravel/horizon/src/Console/SnapshotCommand.php(35): Laravel\\Horizon\\Repositories\\RedisMetricsRepository->snapshot()
#7 [internal function]: Laravel\\Horizon\\Console\\SnapshotCommand->handle()
#8 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#9 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#13 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#14 /home/example/www/staging/releases/119/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#15 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#16 /home/example/www/staging/releases/119/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#17 /home/example/www/staging/releases/119/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /home/example/www/staging/releases/119/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#19 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#20 /home/example/www/staging/releases/119/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#21 /home/example/www/staging/releases/119/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#22 {main}
"}
````

My Horizon and queues are working fine from what I can see, just this error periodically every 10 minutes in the `laravel.log`.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by stu177** [comment]
Ah, managed to figure it out, I had the DEL command disabled on my redis setup so it was failing `RedisMetricsRepository.php:baseSnapshotData()` at `$trans->del($key)`;

I believe I followed the Digital Ocean guide on securing a Redis installation and part of that was renaming dangerous commands and `DEL` was one of them.

I'm not sure if this is common to disable this command or it's an unnecessary step for securing Redis.
