### ISSUE TITLE
Argument 1 passed to Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, bool given

### ISSUE THREAD

**Issue by hefengbao** [laravel/horizon#941]
- Horizon Version: 5.5.0
- Laravel Version: 8.16.1
- PHP Version: 7.4.13
- Redis Driver & Version: predis/phpredis 1.1.6
- Database Driver & Version:  mysql 5.7.32

### Description:
This is today‘s  log, it has been going on for some time。it only alternate write log as below per second， when i delete log file, it stop, but it will  write log again at 0 o'clock。The program runs well, redis no password.

```
[2020-12-02 00:00:00] production.ERROR: NOAUTH Authentication required. {"exception":"[object] (RedisException(code: 0): NOAUTH Authentication required. at /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116)
[stacktrace]
#0 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Redis->lLen()
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(519): Illuminate\\Redis\\Connections\\Connection->command()
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\PhpRedisConnection->command()
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(561): Illuminate\\Redis\\Connections\\Connection->__call()
#4 /var/www/api/vendor/laravel/horizon/src/RedisHorizonCommandQueue.php(52): Illuminate\\Redis\\Connections\\PhpRedisConnection->__call()
#5 /var/www/api/vendor/laravel/horizon/src/Supervisor.php(322): Laravel\\Horizon\\RedisHorizonCommandQueue->pending()
#6 /var/www/api/vendor/laravel/horizon/src/Supervisor.php(293): Laravel\\Horizon\\Supervisor->processPendingCommands()
#7 /var/www/api/vendor/laravel/horizon/src/Supervisor.php(266): Laravel\\Horizon\\Supervisor->loop()
#8 /var/www/api/vendor/laravel/horizon/src/Console/SupervisorCommand.php(92): Laravel\\Horizon\\Supervisor->monitor()
#9 /var/www/api/vendor/laravel/horizon/src/Console/SupervisorCommand.php(67): Laravel\\Horizon\\Console\\SupervisorCommand->start()
#10 [internal function]: Laravel\\Horizon\\Console\\SupervisorCommand->handle()
#11 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#12 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#16 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#17 /var/www/api/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#18 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#19 /var/www/api/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
#20 /var/www/api/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /var/www/api/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#22 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#23 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /var/www/api/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"} 
[2020-12-02 00:00:00] production.ERROR: Argument 1 passed to Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, bool given, called in /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php on line 50 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Laravel\\Horizon\\Repositories\\RedisSupervisorRepository::get() must be of the type array, bool given, called in /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php on line 50 at /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php:70)
[stacktrace]
#0 /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(50): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->get()
#1 /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(99): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->all()
#2 /var/www/api/vendor/laravel/horizon/src/MasterSupervisor.php(165): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->longestActiveTimeout()
#3 /var/www/api/vendor/laravel/horizon/src/ListensForSignals.php(52): Laravel\\Horizon\\MasterSupervisor->terminate()
#4 /var/www/api/vendor/laravel/horizon/src/MasterSupervisor.php(237): Laravel\\Horizon\\MasterSupervisor->processPendingSignals()
#5 /var/www/api/vendor/laravel/horizon/src/MasterSupervisor.php(212): Laravel\\Horizon\\MasterSupervisor->loop()
#6 /var/www/api/vendor/laravel/horizon/src/Console/HorizonCommand.php(63): Laravel\\Horizon\\MasterSupervisor->monitor()
#7 [internal function]: Laravel\\Horizon\\Console\\HorizonCommand->handle()
#8 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#9 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#14 /var/www/api/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#15 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/api/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
#17 /var/www/api/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/api/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#20 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#21 /var/www/api/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#22 {main}
"}
[2020-12-02 00:00:01] production.ERROR: NOAUTH Authentication required. {"exception":"[object] (RedisException(code: 0): NOAUTH Authentication required. at /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116)
[stacktrace]
#0 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Redis->lLen()
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(519): Illuminate\\Redis\\Connections\\Connection->command()
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\PhpRedisConnection->command()
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(561): Illuminate\\Redis\\Connections\\Connection->__call()
#4 /var/www/api/vendor/laravel/horizon/src/RedisHorizonCommandQueue.php(52): Illuminate\\Redis\\Connections\\PhpRedisConnection->__call()
#5 /var/www/api/vendor/laravel/horizon/src/Supervisor.php(322): Laravel\\Horizon\\RedisHorizonCommandQueue->pending()
#6 /var/www/api/vendor/laravel/horizon/src/Supervisor.php(293): Laravel\\Horizon\\Supervisor->processPendingCommands()
#7 /var/www/api/vendor/laravel/horizon/src/Supervisor.php(266): Laravel\\Horizon\\Supervisor->loop()
#8 /var/www/api/vendor/laravel/horizon/src/Console/SupervisorCommand.php(92): Laravel\\Horizon\\Supervisor->monitor()
#9 /var/www/api/vendor/laravel/horizon/src/Console/SupervisorCommand.php(67): Laravel\\Horizon\\Console\\SupervisorCommand->start()
#10 [internal function]: Laravel\\Horizon\\Console\\SupervisorCommand->handle()
#11 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#12 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#16 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#17 /var/www/api/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#18 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#19 /var/www/api/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
#20 /var/www/api/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /var/www/api/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#22 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#23 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /var/www/api/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"} 
[2020-12-02 00:00:01] production.ERROR: Argument 1 passed to Laravel\Horizon\Repositories\RedisSupervisorRepository::get() must be of the type array, bool given, called in /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php on line 50 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Laravel\\Horizon\\Repositories\\RedisSupervisorRepository::get() must be of the type array, bool given, called in /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php on line 50 at /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php:70)
[stacktrace]
#0 /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(50): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->get()
#1 /var/www/api/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(99): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->all()
#2 /var/www/api/vendor/laravel/horizon/src/MasterSupervisor.php(165): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->longestActiveTimeout()
#3 /var/www/api/vendor/laravel/horizon/src/ListensForSignals.php(52): Laravel\\Horizon\\MasterSupervisor->terminate()
#4 /var/www/api/vendor/laravel/horizon/src/MasterSupervisor.php(237): Laravel\\Horizon\\MasterSupervisor->processPendingSignals()
#5 /var/www/api/vendor/laravel/horizon/src/MasterSupervisor.php(212): Laravel\\Horizon\\MasterSupervisor->loop()
#6 /var/www/api/vendor/laravel/horizon/src/Console/HorizonCommand.php(63): Laravel\\Horizon\\MasterSupervisor->monitor()
#7 [internal function]: Laravel\\Horizon\\Console\\HorizonCommand->handle()
#8 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#9 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#14 /var/www/api/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#15 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/api/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run()
#17 /var/www/api/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/api/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/api/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#20 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#21 /var/www/api/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#22 {main}
"} 
```

I make test,:

```
        $horizon = Redis::connection('horizon');
  
        dd($horizon->zrevrangebyscore('supervisors', '+inf',
            CarbonImmutable::now()->subSeconds(29)->getTimestamp()
        ));
```
```
^ array:2 [▼
  0 => "ubuntu-18-4-5dfB:supervisor-2"
  1 => "ubuntu-18-4-5dfB:supervisor-1"
]
```

**Comment by wei-xf** [comment]
Same for me, I use Redis cluster

**Comment by driesvints** [comment]
This is an issue in Predis and nothing we can do about unfortunately: https://github.com/phpredis/phpredis/issues/1757

This issue is already resolved in PhpRedis.

**Comment by CaddyDz** [comment]
```
☁  Redacted [master] php -r 'phpinfo();' | grep -i 'redis version'
Redis Version => 6.0.2
```
Released Dec 16, 2023
Issue persists in PHP Redis
```
☁  Redacted [master] tinker
Psy Shell v0.12.3 (PHP 8.2.23 — cli) by Justin Hileman
> config('database.redis.client');
= "phpredis"
```
