### ISSUE TITLE
Workloads return null on 500+ processes

### ISSUE THREAD

**Issue by jatinthapar1910** [laravel/horizon#958]
version: 
Laravel 5.8, Laravel Horizon 3.0, `predis` as redis client. 

Issue: 
I have a server with 40 cores CPU, 256 GB of RAM dedicated to Redis, Laravel Horizon. 
When I increase the processes to something like 5000 then Dashboard is empty for status, total processes. 
`/horizon/api/workload` returns nothing in response, its empty. 

Logs: 
```
PHP Fatal error:  Uncaught ErrorException: fopen(php://stderr): failed to open stream: operation failed in /var/www/html/laravel/vendor/symfony/console/Output/ConsoleOutput.php:157
#0 /var/www/html/laravel/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/var/ww...', '/var/www/html/l...', 444, Array)
#1 /var/www/html/laravel/vendor/composer/ClassLoader.php(444): include()
#2 /var/www/html/laravel/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/l...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(147): spl_autoload_call('Symfony\\Compone...')
#5 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFrom in /var/www/html/laravel/vendor/composer/ClassLoader.php on line 444
A supervisor with this name is already running.
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
