### ISSUE TITLE
The "rest" option does not exist

### ISSUE THREAD

**Issue by potsky** [laravel/horizon#980]
- Horizon Version: 5.7.0
- Laravel Version: 8.32.1
- PHP Version: 8.0.2
- Redis Driver & Version: ext-redis
- Database Driver & Version:

### Description:

I just have updated laravel/framework and when starting horizon, it loops with this exception:

```
[2021-03-09 16:26:08] local.ERROR: The "rest" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The \"rest\" option does not exist. at /var/www/html/vendor/symfony/console/Input/Input.php:150)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php(111): Symfony\\Component\\Console\\Input\\Input->getOption()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(139): Illuminate\\Console\\Command->option()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Console\\WorkCommand->gatherWorkerOptions()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#4 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\\Queue\\Console\\WorkCommand->handle()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#11 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}
```

### Steps To Reproduce:

- Install last Laravel framework
- Install horizon
- Start horizon

**Comment by driesvints** [comment]
Thanks for reporting this. We've released v5.7.1 which fixes this.
